- hosts: localhost
  user: root
  vars:
      directory: /var/jenkins_home/workspace/lab4/demo
  tasks:

    - name: create docker image
      command: docker build -t demo:latest .
      args:
        chdir: /var/jenkins_home/workspace/lab4/demo

    - name: create tag to push image onto dockerhub
      command: docker tag demo:latest vadimkolodin/demo:latest

    - name: login to docker
      command: docker login -u vadimkolodin -p {{ lookup('ansible.builtin.env', 'DOCKER_PASSWORD') }} docker.io

    - name: push docker image onto dockerhub
      command: docker push vadimkolodin/demo:latest