- hosts: localhost
  user: root
  vars:
      directory: /var/jenkins_home/workspace/lab3/demo
  tasks:

    - name: Build image
      docker_image:
        name: demo
        build:
          path: /var/jenkins_home/workspace/lab3/demo
        source: build

    - name: create docker image
      command: docker build -t demo:latest .

    - name: create tag to push image onto dockerhub
      command: docker tag demo:latest vadimkolodin/demo:latest

    - name: push docker image onto dockerhub
      command: docker push vadimkolodin/demo:latest