- hosts: localhost
  vars:
      directory: /var/jenkins_home/workspace/lab3/demo
  tasks:

    - command: "ls {{directory}}"
      register: dir_out

    - debug: var={{item}}
      with_items: dir_out.stdout_lines

    - name: create docker image
      command: docker build -t demo:latest "demo/_docker"


    - name: create tag to push image onto dockerhub
      command: docker tag demo:latest vadimkolodin/demo:latest

    - name: push docker image onto dockerhub
      command: docker push vadimkolodin/demo:latest