- hosts: localhost
  user: root
  vars:
      directory: /var/jenkins_home/workspace/lab3
  tasks:

    - name: create docker image
      command: docker build -t demo:latest /demo

    - name: create tag to push image onto dockerhub
      command: docker tag demo:latest vadimkolodin/demo:latest

    - name: push docker image onto dockerhub
      command: docker push vadimkolodin/demo:latest