- hosts: localhost
  vars:
      directory: /var/jenkins_home/workspace/lab3/demo
  tasks:

    - name: Install pip3
      yum3:
        name: python3-pip
        state: latest

    - name: Install Docker module for Python (used by Ansible)
      pip:
        name:
          - docker


    - name: test docker
      command: docker --version

    - name: create docker image
      command: docker build -t demo:latest .

    - name: create tag to push image onto dockerhub
      command: docker tag demo:latest vadimkolodin/demo:latest

    - name: push docker image onto dockerhub
      command: docker push vadimkolodin/demo:latest